<?
/**
 * @desc Primary navigation and secondary navigation
 * 
 * @author Steven Rosato
 */
?>

<?
/*
 * Primary navigation
 */
?>
<?=$this->render('default/phpJs/navigation-selection.phtml');?>

<ul class="navigable nav primary-navigation">
	<li>
		<a rel="default/index/index" href="<?=BASE_URL ?>/index">
			<?=$this->_("Accueil")?>
		</a>
	</li>
	<li>
		<a rel="default/therapists/.*" href="<?=BASE_URL ?>/therapists">
			<?=$this->_("Anatothérapeutes")?>
		</a>
	</li>
	<li>
		<a rel="default/comments/.*" href="<?=BASE_URL ?>/comments">
			<?=$this->_("Témoignages")?>
		</a>
	</li>
	<li>
		<a rel="default/services/.*" href="<?=BASE_URL ?>/services/anatotherapy">
			<?=$this->_("Nos soins")?>
		</a>
	</li>
	<li>
		<a rel="default/history/.*" href="<?=BASE_URL ?>/history">
			<?=$this->_("Historique")?>
		</a>
	</li>
	<li>
		<a  rel="default/about/contact" href="<?=BASE_URL ?>/about/contact">
			<?=$this->_("Nous joindre")?>
		</a>
	</li>
</ul>

<div class="clear_both"></div>

<?
/*
 * Secondary navigation
 */
?>
<ul class="navigable nav secondary-navigation">
	<li class="first">
		<a rel="default/anatotherapy/.*" href="<?=BASE_URL?>/anatotherapy">Anatothérapie</a>
	</li>
	<li class="second">
		<a rel="default/training/.*" href="<?=BASE_URL?>/training/corporate">Formation</a>	
	</li>
</ul>

<div class="clear_both"></div>
