<?
/**
 * @desc Renders an optional third navigation pane which should be setup
 * using a placeholder.
 * 
 * The placeholder will, by default, have an ul/li wrapping
 * 
 * @param third-navigation The placeholder key which to put the menu
 * @param key The link name, without the base url
 * @param value (array) 
 * 		0 => The link's rel value for auto-select with the js-selection script
 * 		1 => The link's value
 * 
 * ex:
 * 
 * $this->view->placeholder('third-navigation')->exchangeArray(array(
 *			'#link1' => array(
 *				'default/index/index',  
 *				'Item 1'
 *			),
 *			'#link2' => array(
 *				'default/about/index', 
 *				'Item 2'
 *			)
 *		));
 * 
 * Note: BASE_URL is already prepended to links
 * 
 * @author Steven Rosato 
 */
?>

<? 
/* Capturing content and wapping in ul/li and anchors */
$this->placeholder('third-navigation')->captureStart(Zend_View_Helper_Placeholder_Container::SET);
?>

<? 	if( count($this->placeholder('third-navigation')->getKeys()) ) : ?>
		<ul>
		<?foreach ($this->placeholder('third-navigation') as $key => $data) :?>
			<li><a rel="<?=$data[0]?>" href="<?=BASE_URL . '/' . $key?>"><?=$data[1]?></a></li>
		<?endforeach;?>
		</ul>
<?	endif;?>

<?$this->placeholder('third-navigation')->captureEnd();?>

<? /* Print the navigation panel */ ?>
<?if( strlen(trim($this->placeholder('third-navigation')->getValue())) > 0 ):?>
	<div class="navigable optional-navigation">
		<h6><?=$this->_("Navigation")?></h6>
		<?=$this->placeholder('third-navigation');?>
	</div>
<?endif;?>

<div class="clear_both"></div>