<?= $this->doctype()?>
<html>
<head>
	<? $this->headLink()->prependStylesheet($this->baseUrl() . '/styles/main.css')?> 
	<? $this->headLink()->prependStylesheet(LIB_URL . '/css/common.css')?>
	
	<? $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8') ?>
	
	<?= $this->headMeta()?>
    <?= $this->headLink()?>
    <?= $this->headStyle()?>
    <?= $this->headScript()?>
    
    <?= $this->headTitle($this->generateTitle('Majisti'))?>
</head> 
<body>
	<div class="container">
		<div class="banner"></div>
		<div class="content">
			<?= $this->layout()->content?>
		</div>
		
		<div class="footer">Footer</div>
	</div>
</body>
</html>