<?
/**
 * @desc Contact page
 * 
 * @author Steven Rosato
 */
?>

<div class="contact">
	<h1><?=$this->_("Nous joindre")?></h1>
	<div class="contact-formation">
		<p><?=$this->_("Merci de communiquer avec nous!");?></p>
		<p>
			<?=$this->_("Institut International d’Anatothérapie et <br />Centre d’Anatothérapie Professionnelle")?><br />
			<?=$this->_("16890, rue Mercure")?><br />
			<?=$this->_("St-Hyacinthe (Québec)")?><br />
			J2T 2Y6
		</p>
		<br />
		<table class="center">
			<tr>
				<td><img src="<?=DIR_IMAGES_COMMON?>/icons/phone.png" alt="<?=$this->_('Téléphone')?>" /></td>
				<td class="orange">1-866-869-4001<br />(450) 771-2067</td>
			</tr>
			<tr>
				<td><img src="<?=DIR_IMAGES_COMMON?>/icons/fax.png" alt="<?=$this->_('Télécopie')?>" /></td>
				<td class="orange">(450) 771-6870</td>
			</tr>
			<tr>
				<td><img src="<?=DIR_IMAGES_COMMON?>/icons/mail.png" alt="<?=$this->_('Courriel')?>" /></td>
				<? /* TODO: Protect this email from spam with an ajax call */ ?>
				<td><a href="mailto:infos@anatotherapie.qc.ca">infos@anatotherapie.qc.ca</a></td>
			</tr>
		</table>
	</div>
</div>

