<div class="content_center">
	<? if( !$this->isUserLogged() ) : ?>
	<?=$this->_('Identifiez vous:')?><br /><br />
	<form id="form_login" method="post" action="">
		<table class="login" border="0" cellpadding="0" cellspacing="0">
			<tr><td><?=$this->_('Login:')?></td><td><?=$this->formText('login', $this->login)?></td></tr>
			<tr><td><?=$this->_('Mot de passe:')?></td><td><?=$this->formPassword('pass')?></td></tr>
			<tr><td>&nbsp;</td><td class="right"><?=$this->formSubmit('sub_login', $this->_('Connection'), array('class' => 'btn'))?></td></tr>
		</table>
	<? else:?>
		<a href="<?=$this->redirectionLink('auth/logout')?>">Logout</a>
	<? endif;?>
	</form>
	
	<span style="color: red"><?=empty($this->message) ? '&nbsp;' : $this->message ?></span>
</div>