<?php
/**
 * ************** DO NOT EDIT THIS FILE ******************
 *
 * These constants should have been defined :
 *
 *   LIB_FOLDER    the name of the library folder (ie: 'lib1.3')
 *
 * The following variable will be available in the global scope at the end
 * of this script
 *
 * $applicationPath    the physical path of the application root (where
 *                     application and public folders are)
 * $libPath            the physical path where Zend and Majisti are located
 *
 */

$_delta = create_function('$p,$s', 'while(!empty($p) && !file_exists($p.$s)) {$p=dirname($p);} return $p;');

define('APPLICATION_PATH', $_delta(dirname($_SERVER['SCRIPT_FILENAME']),'/application') );
define('LIB_PATH', $_delta(APPLICATION_PATH,'/'.LIB_FOLDER) . '/' . LIB_FOLDER);

$scriptDir = dirname($_SERVER['SCRIPT_FILENAME']);
$_SERVER['DOCUMENT_ROOT'] = rtrim($_SERVER['DOCUMENT_ROOT'], '/'); // PHP fix to be removed if >= PHP 5.2.8
if ( strlen($scriptDir) == strlen($_SERVER['DOCUMENT_ROOT']) ) {
	define('BASE_URL', '');
} else {
	define('BASE_URL', substr($scriptDir, strlen($_SERVER['DOCUMENT_ROOT'])));
}

/* PHP 5.2.8 removed ending slash after documentRoot */
//$documentRoot = rtrim($_SERVER['DOCUMENT_ROOT'], '/') . '/';

$includePaths = array(LIB_PATH, APPLICATION_PATH, get_include_path());

set_include_path(implode(PATH_SEPARATOR, $includePaths));

require_once 'Zend/Loader.php';
Zend_Loader::registerAutoload();

// cleanup
unset($_delta, $scriptDir, $includePaths);
