<?
/**
 * @desc Not the clearest paginator renderer yet but does a pretty good job.
 * This will generate a default paginator also keeping any $_GET parameters
 * that would be used in a '?param1=foo&param2=bar' fashion.
 * 
 * @author Steven Rosato, Yanick Rochon
 */

?><div class="center"><?php

if ( $this->totalItemCount <= 0 ) {
	print $this->_("No results found.");
} elseif( $this->totalItemCount > $this->itemCountPerPage ) {
	//echo '<hr />';

	// Show page results 
	echo '<p>' 
		. sprintf($this->_('%1$s result(s) found'), '<span class="orange">' . $this->totalItemCount . '</span>')
		. '&nbsp;|&nbsp;'
		. $this->_('Total page count')
		. '&nbsp;<span class="orange">' . $this->pageCount . '</span>'
		. '</p>';

	// First Page to Last Page
	echo '<p>'
		. '<strong>' . $this->_('Go to') . '</strong>:&nbsp;';
		
	if ( $this->current > 1 ) {
		echo '<a href="' . $this->url(array('page' => 1), null, false, false, true) . '">' . $this->_('first page') . '</a>';
	} else {
		echo $this->_('first page');
	}
	
	echo '&nbsp;|&nbsp;';
	
	if ( $this->current < $this->last ) {
		echo '<a href="' . $this->url(array('page' => $this->last), null, false, false, true) . '">' . $this->_('last page') . '</a>';
	} else { 
		echo $this->_('last page');
	}
	

	echo '&nbsp;(' . $this->last . ')' 
		. '</p>';
	
	// End First Page to Last Page 

	//  List pages
	if ($this->pageCount) {
	
		echo '<div class="paginationControl">';
	
		// Previous page link
	
		if (isset($this->previous)) {
	  		echo '<a href="' . $this->url(array('page' => $this->previous), null, false, false, true) . '">&lt;&nbsp;' . $this->_('previous') . '</a>';
		} else {
	  		echo '<span class="disabled">&lt;&nbsp;' . $this->_('previous') . '</span>';
		}
		echo '&nbsp;|';

		// Numbered page links
	
		foreach ($this->pagesInRange as $page) {
			echo "&nbsp;";
	  		if ($page != $this->current) {
	    		echo '<a href="' . $this->url(array('page' => $page), null, false, false, true) . '">' . $page . '</a>';
			} else {
	    		echo $page;
			}
			echo '&nbsp;|';
		}

		echo "&nbsp;";		
		// Next page link
		if (isset($this->next)) {
	  		echo '<a href="' . $this->url(array('page' => $this->next), null, false, false, true) . '">' . $this->_('next') . '&nbsp;&gt;</a>';
		} else {
			echo '<span class="disabled">' . $this->_('next') . '&nbsp;&gt;</span>';
		}
		
		echo '</div>';
		
	}
	// End list pages
	
}

?></div><?php

if ( $this->totalItemCount <= 0 ) {
	//echo '<hr />';
}