<?
/**
 * @desc The fees listing, this one has a custom rendering
 * 
 * @author Steven Rosato
 */
?>

<h1><?=$this->_("Nos tarifs")?></h1>

<?
$products = Anato_Center::getInstance()->getServicesModel()->fees->getProductList();
?>
<table>
	<? foreach ($products as $product) :?>
		<tr>
			<td>
				<?=$product['val']?>	
			</td>
			<td class="bold">
				<?=$product['fee']?>$
			</td>	
		</tr>	
	<? endforeach;?>
</table>
<br />
* Prix sujets à changement