<?
/**
 * @desc Language bar.
 *
 * @author Majisti
 */

$locales = $this->locales();

$content = pq('<div />')
    ->addClass('language-bar')
;

$separator = isset($this->separator)
           ? $this->separator
           : ' | ';

/* @var $locale \Zend_Locale */
$counter = 0;
foreach ($locales->getLocales() as $key => $locale) {
    if( $locale->equals($locales->getCurrentLocale()) ) {
        continue;
    }

    $content->append(pq('<span />')
        ->append(pq('<a />')
            ->attr('href', $this->url(array('lang' => $locale->toString())))
            ->html(ucfirst($locale->getTranslation($locale->getLanguage(), 'language',
                $locale->getLanguage())))
        )
    );
    $counter++;

    /* add separator */
    if( $counter < count($locales->getLocales()) - 1) {
        $content->append(pq('<span />')
            ->addClass('separator')
            ->html($separator)
        );
    }
}

$this->setRenderReturn($content);
