<?
/**
 * @desc The admin's navigation
 * 
 * @author Steven Rosato
 */
?>

<div class="navigable admin-nav-wrapper">
	<ul class="admin-primary-navigation">
		<li>
			<a rel="admin/therapists/.*" href="<?=BASE_URL?>/admin/therapists/list">
				<?=$this->_("Anatothérapeutes");?>
			</a>
		</li>
	</ul>
	
	<? if( 'therapists' === $this->request()->getControllerName() ) { ?>
	<ul class="admin-secondary-navigation">
		<li>
			<a rel="admin/therapists/add" href="<?=BASE_URL?>/admin/therapists/add">
				<?=$this->_("Ajouter")?>
			</a>
		</li>
		<li>
			<a rel="admin/therapists/list" href="<?=BASE_URL?>/admin/therapists/list">
				<?=$this->_("Lister")?>
			</a>
		</li>
		<li>
			<a rel="admin/therapists/search" href="<?=BASE_URL?>/admin/therapists/search">
				<?=$this->_("Rechercher")?>
			</a>
		</li>
	</ul>
	<? } ?>
	
	<div class="clear_both"></div>
</div>