<?php

/* @var $content \MajistiX\Editing\Model\Content */
/* @var $editor \MajistiX\Editing\View\Editor\IEditor */

$content = $this->content;
$editor  = $this->editor;

$container = pq('<div />')
    ->addClass('maj-editing-container')
    ->attr('id', 'maj-editing-container-' . $content->getName())
    /* content */
    ->append(pq('<div />')
        ->addClass('text-wrapper')
        /* panel */
        ->append(pq('<div />')
            ->addClass('panel')
            ->append(pq('<a />')
                ->addClass('edit')
                ->attr('href', '#')
                ->attr('rel', $content->getName())
            )
        )
        ->append(pq('<div />')
            ->addClass('text')
            ->html($content->getContent())
        )
    )
    ->append(pq('<div />')
        ->addClass('message')
    )
    ->append(pq('<div />')
        ->attr('id', 'majistix-editing-cancel-dialog-' . $content->getName())
        ->attr('title', $this->_("Cancel changes"))
        ->html($this->_("Are you sure you want to close the editor and cancel your changes?"))
    )
    /* editor */
    ->append($editor->createForm($content)->render())
;

$this->setRenderReturn($container);
