<?php

/* @var $content \MajistiX\Editing\Model\Content */
/* @var $editor \MajistiX\Editing\View\Editor\IEditor */

$content = $this->content;
$editor  = $this->editor;

$container = pq('<div />')
    ->addClass('maj-editing-container')
    /* content */
    ->append(pq('<div />')
        ->addClass('text-wrapper')
        ->append(pq('<div />')
            ->addClass('text')
            ->html($content->getContent())
        )
        /* panel */
        ->append(pq('<div />')
            ->addClass('panel')
            ->append(pq('<a />')
                ->addClass('edit')
                ->attr('href', '#')
                ->attr('rel', $content->getName())
            )
        )
    )
    ->append(pq('<div />')
        ->addClass('message')
    )
    /* editor */
    ->append($editor->createForm($content)->render())
;

$this->setRenderReturn($container);
