<?
/**
 * @desc The js pagination control based on the sample code
 * given from the jQuery table sorter at http://tablesorter.com
 * 
 * @author Steven Rosato and tablesorter.com 
 */
?>

<!-- js pagination control -->
<div id="pager" class="pager margin_top20">
	<form action=""><div>
		<img src="<?=LIB_URL?>/images/icons/pagination/tablesorter/first.png" class="first"/>
		<img src="<?=LIB_URL?>/images/icons/pagination/tablesorter/prev.png" class="prev"/>
		
		<input type="text" class="pagedisplay" size="3" readonly="readonly" />
		
		<img src="<?=LIB_URL?>/images/icons/pagination/tablesorter/next.png" class="next"/>
		<img src="<?=LIB_URL?>/images/icons/pagination/tablesorter/last.png" class="last"/>
		
		<select class="pagesize">
			<option selected="selected"  value="10">10</option>
			<option value="20">20</option>
			<option value="30">30</option>
		</select>
	</div></form>
</div>
<br /><br /><br />