<?
/**
 * @desc History discovery page
 * 
 * @author Steven Rosato
 */
?>

<h1><?=$this->_("Découverte de l’anatothérapie")?></h1>

<?$discovery = new Majisti_Object($this->history->getDiscovery());?>

<div class="float_left margin_right20 center">
	<img 
		 src="<?=DIR_IMAGES_COMMON?>/body/history/founder.jpg" 
		 alt="Mme Noëlla Potvin" 
	/><br />
	<span class="bold"><?=$discovery->author?></span>
</div>

<?=$this->partial('default/blocks/paragraph.phtml', array('model' => $discovery->data));?>
