<?
/**
 * @desc Founder's biography page
 * 
 * @author Steven Rosato
 */
?>

<div id="top"></div>

<h1><?=$this->_("Biographie de la fondatrice")?></h1>

<?$bio = new Majisti_Object($this->history->getFounderBiography());?>

<? /* description */ ?>
<p><?=$bio->desc?></p>

<?
	/* anchors */
	foreach ($bio->anchors->a as $link) {
		print "<a rel=\"{$link->href}\" class=\"scrollTo\" href=\"javascript:void(0)\">{$link->text}</a><br />";
	}
	
	/* text blocks */
	foreach ($bio->block as $block) {
		print "<a id=\"{$block->anchor}\"></a>";
		
		print "<p class=\"bold\">{$block->title}</p>";
		
		foreach ($block->p as $p) {
			print "<p>{$p}</p>";
		}
		
		print '<a rel="top" class="scrollTo" href="javascript:void(0)">Haut de page</a>';
	}
?>