<?
/**
 * @desc This is the default block partial.
 * Will render a title, a short text,
 * an unordered list along with a link
 * (though all elements are optionnal)
 * 
 * @param class The wrapper's class
 * @param title [opt] The block's title
 * @param content [opt; def=&nbsp;] The block's content
 * @param Array list [opt] The block's unordered list in a key-value paired array('link' => 'value')
 * 	or array('value') only if you want no links
 * @param postListContent [opt] Will add an addtionnal paragraph of content after the list
 * @param link [opt] The block's link as link = array('link', 'value')
 * 
 * Note: anchors (links) already have the BASE_URL . '/' prepended
 * 
 * @author Steven Rosato
 */
?>

<div class="default-block-wrapper <?=$this->class?>">
	<?	/* title */
		if( !empty($this->title) ):?>
			<h4 class="default-block-title"><?=$this->title?></h4>
	<?	endif;?>
	
	<?	/* content */
		if( !empty($this->content) ):?>
			<div class="default-block-content">
				<?=$this->content?>
			</div>
	<?	endif;?>
	
	<?	/* list */
		if( !empty($this->list) && count($this->list) ):?>
			<ul class="default-block-list">
				<?foreach ($this->list as $key => $value) :?>
					<?if( is_int($key) ):?>
						<li><?=$value?></li>
					<?else:?>
						<li><a href="<?=BASE_URL . '/' . $key?>"><?=$value?></a></li>
					<?endif;?>
				<?endforeach;?>
			</ul>
	<?	endif;?>
	
	<?	/* post list content */
		if( !empty($this->postListContent) ):?>
			<p><?=$this->postListContent?></p>
	<?	endif;?>
	
	<?	/* link */
		if( !empty($this->link) ):?>
			<a href="<?=BASE_URL . '/' . $this->link[0]?>"><?=$this->link[1]?>&nbsp;&gt;&gt;&gt;</a>
	<?	endif;?>
</div>
