<?
/**
 * @desc Region partial, prints a rowset region and all its related therapists
 * with the regions list on top.
 * 
 * @param regions The regions object key
 * 
 * @author Steven Rosato
 */

$regions = $this->regions;

if( null !== $regions ) {
	foreach ($regions as $region) {
		$therapists = $region->findTherapistsViaTherapistsRegions();
		
		if( count($therapists) ) {
			print '<h6>' . $region->name . ':</h6>';
			print '<a id="' . $region->id . '"></a>';
			
			print $this->partial()
				->setObjectKey('therapists')
				->partial('default/blocks/therapist.phtml', $therapists
			);
			
			print '<p><a rel="regionsList" class="scrollTo" href="javascript:void(0)">Retourner en haut</a></p>';
		}		
	}
}
?>