<?
/**
 * @desc This is the service partial.
 * It will render a single service's products list
 * 
 * @param model an Anato_Service
 * 
 * @author Steven Rosato
 */

if( !($this->model instanceof Anato_Service) ) {
	throw new Majisti_Exception("Model not instance of Anato_Service");
}
?>

<div class="service-block-wrapper">
	<?if( strlen($this->model->getName()) > 0 ):?>
		<h1><?=$this->model->getName()?></h1>
	<?endif;?>
	
	<?if( strlen($this->model->getDescription()) > 0 ):?>
		<p><?=$this->model->getDescription()?></p>
	<?endif;?>
	
	<?if( count($this->model->getProductList()) ):?>
		<ul>
			<?=$this->partial(
				'default/blocks/service/product.phtml', 
				array('model' => $this->model->getProductList())
			);
			?>
		</ul>
	<?endif;?>
</div>

