<!--  Displaying Item Model(s) infos in a looping partial -->

    <dt><?= $this->title ?></dt>
    <dd>
   		<div class="subscription_info_wrapper">
    	<?
    		if(is_array($this->value)) {
    			foreach($this->value as $singleValue) {
    				print $singleValue . "<br />";
    			}
    		} else {
    			print $this->value;
    		}
   		?>
   		</div>
   		<? 
   		if($this->key == 'attributes') {
		echo "<hr />";
		}
		?>
    </dd>