<?
/*
 * Block 1
 */
$content = $this->_("<p>Enfin la solution à vos problèmes de santé : arthrose, burn-out, bursite,
cellulite, dépression, entorse, fibromyalgie, hernie, maux de dos, migraines, tendinite, etc...</p>

<p>Des résultats étonnants ont été obtenus depuis que l’anatothérapie existe.</p>
 
<p>Cette approche thérapeutique répare les blocages musculaires, diminue la douleur, active la circulation, 
réduit le stress et régénère le corps.</p>");

print $this->partial('default/blocks/default.phtml', array(
	'class'		=> 'block1',
	'title' 	=> $this->_("L’Anatothérapie : une technique révolutionnaire, <br /><span style='padding-left:145px;'>curative, préventive et à résultats…</span>"),
	'content' 	=> $content,
	'link'		=> array('default/anatotherapy/index', $this->_("Voir l'Anatothérapie"))
));


/*
 * Block 2
 */
print $this->partial('default/blocks/default.phtml', array(
	'class'	=> 'block2',
	'title'	=> $this->_("L’Institut International d’Anatothérapie"),
	'content' => $this->_("Offre une nouvelle profession valorisante"),
	'list'	=> array(
		$this->_("Pour vous qui aimez aider les gens"),
		$this->_("Pour vous qui aimez résoudre les problèmes de santé"),
		$this->_("Pour vous qui avez l’âme d’un(e) thérapeute"),
		$this->_("Pour vous qui aimez être à la fine pointe des nouvelles techniques…"),
	),
	'postListContent' => $this->_("L’Institut  est le seul établissement d’enseignement qui donne la 
		formation en anatothérapie au Canada. À ce titre, nous sommes enregistrés et 
		accrédités comme établissement d’enseignement reconnu par le Ministère du Revenu 
		du Québec et l’Agence du revenu du Canada."
	),
	'link'	=> array('default/training/index', $this->_("Voir formation"))
));

/*
 * Block 3
 */
print $this->partial('default/blocks/default.phtml', array(
	'class'	=> 'block3',
	'title' => $this->_("Le centre d'Anatothérapie Professionnelle"),
	'content' => $this->_("Vous propose:"),
	'list'	=> array(
		$this->_("L'Anatothérapie"),
		$this->_("L'Anatobalayage"),
		$this->_("L'Anatomassage"),
		$this->_("Des certificats cadeaux"),
	),
	'link'	=> array('default/services/index', $this->_("Voir tous nos soins"))
));
?>
