<?
/**
 * @desc Therapists listing
 * 
 * @author Steven Rosato
 */

$regions = $this->regions->getAll();
?>

<!--  <h1><?//=$this->_("Liste des anatothérapeutes");?></h1> -->
<h1><?=$this->_("Nos anatothérapeutes ayant leur droit de pratique valide et désirant être sur ce site");?></h1>

<a id="regionsList"></a>
<ul class="float_left">
<?
$i=0;
foreach ($regions as $region) {
	if( count($region->findTherapistsViaTherapistsRegions()) ) {
		if(  $i++ - 1 === (int)(count($regions) / 2) ) {?>
			</ul><ul class="float_left margin_left100 inline">
		<?}?> 
		<li><a rel="<?=$region->id?>" class="scrollTo" href="javascript:void(0)"><?=$region->name?></a></li> 
	<?}?>
<?}?>
</ul>

<div class="clear_left"></div>

<?=$this->partial()
	->setObjectKey('regions')
	->partial('default/blocks/region.phtml', $regions
);?>