<h1><?=$this->_("Informations de l'anatothérapeute")?></h1>

<p>
	<a href="<?=BASE_URL?>/therapists"><?=$this->_("Retourner à la liste")?></a>
</p>

<?$therapist = $this->therapist?>

<script type="text/javascript">
	$(function(){
		$('.therapists tr').each(function() {
			$(this).children(':first').addClass('first');
		});
	});
</script>

<table class="therapists">
	<tr>
		<td><?=$this->_("Nom:")?></td>
		<td><?=$therapist->name?></td>
	</tr>
	<tr>
		<td><?=$this->_("Prénom:")?></td>
		<td><?=$therapist->fName?></td>
	</tr>
	<tr>
		<td><?=$this->_("Adresse:")?></td>
		<td>
			<?if( 1 === $this->addressIsPrivate ) :?>
				<span class='italic'>
					<?=$this->_("L'anatothérapeute préfère garder son adresse privée. Veuillez s.v.p le contacter.");?>
				</span>
			<?else:?>
				<?=$therapist->address?>
			<?endif;?>
		</td>
	</tr>
	<tr>
		<td><?=$this->_("Téléphone:")?></td>
		<td><?=$therapist->phone?></td>
	</tr>
	<?if( null != $therapist->fax ):?>
	<tr>
		<td><?=$this->_("Télécopieur:")?></td>
		<td><?=$therapist->fax?></td>
	</tr>
	<?endif;?>
	<tr>
		<td><?=$this->_("Courriel:")?></td>
		<td><?=$therapist->email?></td>
	</tr>
	<tr>
		<td><?=$this->_("Autres informations:")?></td>
		<td>
			<?if( null == $therapist->infos || empty($therapist->infos) ): ?>
				Aucune autre information disponible
			<?else:?>
				<?=$therapist->infos?>
			<?endif;?>
		</td>
	</tr>
</table>