<?
/**
 * @desc Language bar.
 *
 * @author Majisti
 */

$locales = $this->locales();

$content = pq('<div />')
    ->addClass('language-bar')
;

/* @var $locale \Zend_Locale */
foreach ($locales->getLocales() as $locale) {
    if( $locale->equals($locales->getCurrentLocale()) ) {
        continue;
    }

    $content->append(pq('<a />')
        ->attr('href', $this->url(array('lang' => $locale->toString())))
        ->html(ucfirst($locale->getTranslation($locale->getLanguage(), 'language',
            $locale->getLanguage())))
    );
}

$this->setRenderReturn($content);
