<?
/**
 * @desc Treated problems displayed in a two column fashion
 * 
 * This partial is also rendered from the anatotherapy service action
 * hence the default variables title and desc
 * 
 * @author Steven Rosato
 */

if( !isset( $this->title ) ) {
	$this->title = $this->_("Problèmes de santé de A à Z pouvant être traités par l’anatothérapie");
}
?>

<?
$treatableProblems = Anato_Center::getInstance()->getTherapyModel()->getTreatableProblems();
$maxPerColumns = 40;
?>

<div class="treated-problems">
	<h1><?=$this->title?></h1>
	
	<?if(isset($this->desc)){
		print '<p>' . $this->desc . '</p>';
	}?>
	
	<ul>
		<?
		$i = 0;
		foreach ($treatableProblems as $problem) :?>
			<?if( !($i % $maxPerColumns > 0 || $i === 0 || $problem == end($treatableProblems)) ): ?>
				</ul><ul>
			<?endif;?>
			<li><?=$problem?></li>
			<?$i++?>
		<?endforeach;?>
	</ul>
	
	<div class="clear_left"></div>
	
	<p class="others">et plusieurs autres...</p>
</div>
