<?
/**
 * @desc The default layout
 * 
 * @author Steven Rosato
 */
?>

<?= $this->doctype()?>
<html>
<head>
	<? $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8') ?>
	
	<?= $this->jQuery()?>
	
	<?= $this->headMeta()?>
    <?= $this->headLink()?>
    <?= $this->headStyle()?>
    <?= $this->headScript()?>
    
    <?= $this->headTitle($this->generateTitle('Anatothérapie'))?>
</head> 
<body>
	<div class="container">
		<?=$this->render('default/header.phtml');?>
		<div class="water-bg"><div class="butterfly"><div class="health-bg"><div class="butterfly-bg">
			<div class="content"><div class="content-bg">
				<?
				print $this->render('default/admin.phtml');
				print $this->layout()->content;
				?>
			</div></div>
			<?=$this->render('default/optional-navigation.phtml');?>
		</div></div></div></div>
		<?= $this->render('default/footer.phtml');?>
	</div>
</body>
</html>