<?= $this->doctype()?>
<html>
<head>
	<? $this->headLink()->prependStylesheet($this->baseUrl() . '/styles/core.css')?> 
	<? $this->headLink()->prependStylesheet(LIB_URL . '/styles/common.css')?>
	
	<? $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8') ?>
	
	<?= $this->headMeta()?>
    <?= $this->headLink()?>
    <?= $this->headStyle()?>
    <?= $this->headScript()?>
    
    <?= $this->headTitle('Under Construction')?>
	</style>
</head> 
<body>
	<div class="logo"></div>
	<div class="construction">
		<p>Website under construction</p>
		<p>Site en construction</p>
	</div>
</body>
</html>